[build]
  publish = "_site"  # Directorio de salida donde Quarto coloca los archivos generados
  command = "quarto render"  # Comando para construir el sitio

[[plugins]]
  package = "@quarto/netlify-plugin-quarto"  # Plugin de Quarto para Netlify
